# Generated by Django 5.0 on 2024-01-02 02:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('samples', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('identification', models.IntegerField()),
                ('name', models.CharField(max_length=500)),
                ('last_name', models.CharField(max_length=500)),
                ('sample', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='samples.sample')),
            ],
        ),
    ]
