# Generated by Django 5.0 on 2024-01-02 02:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0002_rename_location_id_sample_location'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Users',
            new_name='User',
        ),
    ]
