# Generated by Django 4.2.9 on 2024-03-11 01:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('samples', '0001_initial'),
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('duration', models.DurationField()),
                ('id_event', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='event.event')),
                ('id_sample', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='samples.sample')),
            ],
        ),
    ]
