# Generated by Django 5.0 on 2024-01-02 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('location_id', models.IntegerField()),
                ('location_name', models.CharField(max_length=500)),
            ],
        ),
    ]
