# Generated by Django 4.2.9 on 2024-03-11 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('id_sample', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=500)),
                ('date', models.DateField()),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('value_PM2', models.DecimalField(decimal_places=6, max_digits=6)),
                ('temperature', models.DecimalField(decimal_places=6, max_digits=6)),
                ('humidity', models.DecimalField(decimal_places=6, max_digits=6)),
                ('neighbourhood', models.CharField(max_length=100)),
            ],
        ),
    ]
