# Generated by Django 5.0 on 2024-01-02 02:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=500)),
                ('sample', models.IntegerField()),
                ('location_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='locations.location')),
            ],
        ),
    ]
